name: flat-tomorrow
on:
  schedule:
    - cron: 23 19 * * *
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=dateYear::$(date -d "tomorrow" +%Y)"
          echo "::set-output name=dateMonth::$(date -d "tomorrow" +%m)"
          echo "::set-output name=dateDay::$(date -d "tomorrow" +%d)"
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Flat Data
        uses: githubocto/flat@v3.3.1
        with:
          http_url: https://api.esios.ree.es/archives/70/download_json?date={{ steps.date.outputs.dateDay }}-{{ steps.date.outputs.dateMonth }}-{{ steps.date.outputs.dateYear }}
          downloaded_filename: public/data/price.json
          authorization: ${{ secrets.API_KEY }}
          postprocess: tomorrow.js
