name: flat
on:
  schedule:
    - cron: '55 22 * * *'
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "date_tomorrow=$(date -d "tomorrow" +'%d-%m-%Y')" >> $GITHUB_OUTPUT
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Flat Data
        uses: githubocto/flat@v3.3.1
        with:
          http_url: https://api.esios.ree.es/archives/70/download_json?date=${{ steps.date.outputs.date_tomorrow }}
          downloaded_filename: public/data/price.json
          authorization: ${{ secrets.API_KEY }}
          postprocess: update_create_datasets.js
