name: flat-omie
on:
  schedule:
    - cron: 15 12 * * *
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -d 'tomorrow' +%Y%m%d)"
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "1.8.2"
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Flat Data
        uses: githubocto/flat@3.4.0
        with:
          http_url: https://www.omie.es/es/file-access-list?parents=/Mercado%20Diario/1.%20Precios&dir=Precios%20horarios%20del%20mercado%20diario%20en%20Espa%C3%B1a&realdir=marginalpdbc
          downloaded_filename: public/data/omie_prices.json
          postprocess: omie_dataset.js
