name: flat-omie
on:
  schedule:
    - cron: 25 13 * * *
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -d 'tomorrow' +%Y%m%d)"
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.omie.es/es/file-download?parents%5B0%5D=marginalpdbc&filename=marginalpdbc_${{ steps.date.outputs.date }}.1
          downloaded_filename: public/data/omie_prices.json
          postprocess: omie_dataset.js
